#! /bin/bash
echo 'Git commit successful. Running test suite'
homedir=$(git rev-parse --show-toplevel)
cd $homedir
#python3 -m test.test_csv
#echo 'Test suite ended'

cd doc/code
python -m pdoc ../code/* -o .
echo 'Regenerated documentation post commit'